### ISSUE TITLE
安装Plugins-manager 的问题

### ISSUE THREAD

**Issue by jjeejj** [aimer1124/jmeter-tutorial#2]
我在安装 这个插件管理器的遇到了一个问题： 

就是下载 `jmeter-plugins-manager-1.3.jar`  这个 jar 包后，放到 `lib\ext` 文件夹下，然后重新启动 `Jmeter` ， 在 `Options` 菜单下没有 `Plugins Manager` 这个菜单，这是因为什么呢？

![image](https://user-images.githubusercontent.com/15176971/51789217-80833d00-21c1-11e9-9d8d-d2f53738e483.png)

环境：
系统： `MacOs Mojave  10.14`
JDK:  `1.8.0_121`
Jmeter: `5.0`
jmeter-plugins-manager-1.3.jar: `1.3`

**Comment by aimer1124** [comment]
@jjeejj
plugin-manager安装好了之后，启动JMeter时，是否有报错？
看一下控制台的信息

**Comment by jjeejj** [comment]
没有报错，如果有报错的就清晰了
![image](https://user-images.githubusercontent.com/15176971/51800885-6d2faa80-2271-11e9-92ee-ffaacfa17035.png)
这是常规提示

**Comment by aimer1124** [comment]
@jjeejj 
能否再确认下plugin-manager是否正确正确？
- 下载地址：[https://jmeter-plugins.org/get/](https://jmeter-plugins.org/get/)
- 存放位置：`lib/ext`

**Comment by jjeejj** [comment]
没问题，已经正确下载安装

**Comment by aimer1124** [comment]
如果plugin-manager没有问题，那么建议看一下是不是java与plugin-manager不兼容，引起的。
有两个方向：
- 更新java版本至最新
- 确保使用的是JDK，非JRE

**Comment by aimer1124** [comment]
2天未收到新的回复，暂时关闭此问题
